import type { Metadata } from "next";
import { Inter, Roboto, Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({ subsets: ["latin"], style: ["normal"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Next-Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prompt.className}>{children}</body>
    </html>
  );
}
